### POST a report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 1980,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 10000
}

### Patch approve report
PATCH http://localhost:3000/reports/6
Content-Type: application/json

{
    "approved": true
}

### GET reports by query
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=100000&year=1980